from __future__ import print_function

import os
import json
import pickle
import sys
import traceback
import numpy as np
import pandas as pd
from sklearn import tree

prefix = '/opt/ml/'

input_path = prefix + 'input/data'
output_path = os.path.join(prefix, 'output')
model_path = os.path.join(prefix, 'model')
param_path = os.path.join(prefix, 'input/config/hyperparameters.json')

channel_name='training'
training_path = os.path.join(input_path, channel_name)

def train():
    print('Starting the training.')
    try:
        df=pd.read_csv('s3://your_bucket/DadosTeseLogit.csv',sep=',',header=0)
        sel=np.where(df.corr()['selected']>.5)[0][0:-1]
        df=df.iloc[:,np.concatenate([[30],sel])]
        raw_data = df
        train_data = df
        train_y = train_data.ix[:,0]
        train_X = train_data.ix[:,1:]

        clf = tree.DecisionTreeClassifier(max_depth:20,max_features:None)
        clf = clf.fit(train_X, train_y)

        with open(os.path.join(model_path, 'decision-tree-model.pkl'), 'w') as out:
            pickle.dump(clf, out)
        print('Training complete.')
    except Exception as e:
        trc = traceback.format_exc()
        with open(os.path.join(output_path, 'failure'), 'w') as s:
            s.write('Exception during training: ' + str(e) + '\n' + trc)
        print('Exception during training: ' + str(e) + '\n' + trc, file=sys.stderr)
        sys.exit(255)

if __name__ == '__main__':
    train()

    # A zero exit code causes the job to be marked a Succeeded.
    sys.exit(0)
